//! wasm2cor24 library
//!
//! Provides WASM to COR24 translation and full pipeline support.

mod pipeline;

pub use pipeline::{run_pipeline, print_leds};

use anyhow::Result;
use wasmparser::{FuncType, Operator, Parser, Payload};

/// Translate WASM binary to COR24 assembly
pub fn translate_wasm(wasm: &[u8]) -> Result<String> {
    let mut output = String::new();
    output.push_str("; COR24 Assembly - Generated by wasm2cor24\n");
    output.push_str("; From Rust source via WASM\n\n");

    let mut types: Vec<FuncType> = Vec::new();
    let mut func_types: Vec<u32> = Vec::new();
    let mut exports: Vec<(String, u32)> = Vec::new();

    // First pass: collect metadata
    for payload in Parser::new(0).parse_all(wasm) {
        match payload? {
            Payload::TypeSection(reader) => {
                for rec_group in reader {
                    let rec_group = rec_group?;
                    for ty in rec_group.into_types() {
                        if let wasmparser::CompositeType::Func(ft) = ty.composite_type {
                            types.push(ft);
                        }
                    }
                }
            }
            Payload::FunctionSection(reader) => {
                for func in reader {
                    func_types.push(func?);
                }
            }
            Payload::ExportSection(reader) => {
                for export in reader {
                    let export = export?;
                    if let wasmparser::ExternalKind::Func = export.kind {
                        exports.push((export.name.to_string(), export.index));
                    }
                }
            }
            _ => {}
        }
    }

    // Second pass: translate code
    let mut func_index = 0;
    for payload in Parser::new(0).parse_all(wasm) {
        if let Payload::CodeSectionEntry(body) = payload? {
            let type_idx = func_types.get(func_index).copied().unwrap_or(0) as usize;
            let func_type = types.get(type_idx);

            let func_name = exports
                .iter()
                .find(|(_, idx)| *idx == func_index as u32)
                .map(|(name, _)| name.clone())
                .unwrap_or_else(|| format!("func_{}", func_index));

            output.push_str(&translate_function(&func_name, func_type, body)?);
            func_index += 1;
        }
    }

    Ok(output)
}

fn translate_function(
    name: &str,
    func_type: Option<&FuncType>,
    body: wasmparser::FunctionBody,
) -> Result<String> {
    let mut output = String::new();

    // Function header
    output.push_str(&format!("; Function: {}\n", name));
    if let Some(ft) = func_type {
        output.push_str(&format!(
            "; Signature: ({}) -> {}\n",
            ft.params()
                .iter()
                .map(|t| format!("{:?}", t))
                .collect::<Vec<_>>()
                .join(", "),
            if ft.results().is_empty() {
                "void".to_string()
            } else {
                ft.results()
                    .iter()
                    .map(|t| format!("{:?}", t))
                    .collect::<Vec<_>>()
                    .join(", ")
            }
        ));
    }
    output.push_str(&format!("{}:\n", name));

    // Parse locals
    let mut locals_reader = body.get_locals_reader()?;
    let mut num_locals: u32 = 0;

    for _ in 0..locals_reader.get_count() {
        let (count, _ty) = locals_reader.read()?;
        num_locals += count;
    }

    // Get parameter count from function type
    let num_params = func_type.map(|ft| ft.params().len() as u32).unwrap_or(0);
    let total_locals = num_params + num_locals;

    // Always use prologue for stack-based locals (avoids register conflicts)
    output.push_str("        push    fp\n");
    output.push_str("        mov     fp, sp\n");
    if total_locals > 0 {
        output.push_str(&format!("        add     sp, -{}\n", total_locals * 3));
        // Copy parameters from registers to stack frame
        for i in 0..num_params {
            let offset = i * 3;
            output.push_str(&format!("        sw      r{}, {}(fp)\n", i, offset));
        }
    }

    // Track state
    let mut stack_depth: i32 = 0;
    let mut code = Vec::new();
    let mut label_counter = 0;
    let mut block_stack: Vec<(String, String)> = Vec::new();

    // Parse operators
    let ops_reader = body.get_operators_reader()?;
    for op in ops_reader {
        let op = op?;
        match op {
            Operator::LocalGet { local_index } => {
                let offset = local_index * 3;
                code.push(format!("        lw      r{}, {}(fp)\n", stack_depth, offset));
                stack_depth += 1;
            }

            Operator::LocalSet { local_index } => {
                stack_depth -= 1;
                let offset = local_index * 3;
                code.push(format!("        sw      r{}, {}(fp)\n", stack_depth, offset));
            }

            Operator::I32Const { value } => {
                if value >= -128 && value <= 127 {
                    code.push(format!("        lc      r{}, {}\n", stack_depth, value));
                } else {
                    code.push(format!("        la      r{}, 0x{:06X}\n", stack_depth, value as u32 & 0xFFFFFF));
                }
                stack_depth += 1;
            }

            Operator::I32Add => {
                stack_depth -= 1;
                code.push(format!("        add     r{}, r{}\n", stack_depth - 1, stack_depth));
            }

            Operator::I32Sub => {
                stack_depth -= 1;
                code.push(format!("        sub     r{}, r{}\n", stack_depth - 1, stack_depth));
            }

            Operator::I32And => {
                stack_depth -= 1;
                code.push(format!("        and     r{}, r{}\n", stack_depth - 1, stack_depth));
            }

            Operator::I32Or => {
                stack_depth -= 1;
                code.push(format!("        or      r{}, r{}\n", stack_depth - 1, stack_depth));
            }

            Operator::I32Store8 { memarg } => {
                stack_depth -= 2;
                let addr_reg = stack_depth;
                let val_reg = stack_depth + 1;
                if memarg.offset > 0 {
                    code.push(format!("        la      r{}, 0x{:06X}\n", val_reg + 1, memarg.offset as u32 & 0xFFFFFF));
                    code.push(format!("        add     r{}, r{}\n", addr_reg, val_reg + 1));
                }
                code.push(format!("        sb      r{}, 0(r{})\n", val_reg, addr_reg));
            }

            Operator::Loop { .. } => {
                let start = format!(".L{}", label_counter);
                let end = format!(".L{}", label_counter + 1);
                label_counter += 2;
                block_stack.push((start.clone(), end));
                code.push(format!("{}:\n", start));
            }

            Operator::Block { .. } => {
                let start = format!(".L{}", label_counter);
                let end = format!(".L{}", label_counter + 1);
                label_counter += 2;
                block_stack.push((start, end));
            }

            Operator::BrIf { relative_depth } => {
                stack_depth -= 1;
                if let Some((start, _)) = block_stack.iter().rev().nth(relative_depth as usize) {
                    code.push(format!("        ceq     r{}, z\n", stack_depth));
                    code.push(format!("        brf     {}\n", start));
                }
            }

            Operator::Br { relative_depth } => {
                if let Some((start, _)) = block_stack.iter().rev().nth(relative_depth as usize) {
                    code.push(format!("        bra     {}\n", start));
                }
            }

            Operator::I32LtU => {
                stack_depth -= 1;
                code.push(format!("        clu     r{}, r{}\n", stack_depth - 1, stack_depth));
                code.push(format!("        mov     r{}, c\n", stack_depth - 1));
            }

            Operator::I32Eqz => {
                code.push(format!("        ceq     r{}, z\n", stack_depth - 1));
                code.push(format!("        mov     r{}, c\n", stack_depth - 1));
            }

            Operator::End => {
                if let Some((_, end)) = block_stack.pop() {
                    code.push(format!("{}:\n", end));
                }
            }

            Operator::Return => {
                code.push("        mov     sp, fp\n".to_string());
                code.push("        pop     fp\n".to_string());
                code.push("        jmp     (r1)\n".to_string());
            }

            Operator::Drop => {
                stack_depth -= 1;
            }

            other => {
                code.push(format!("        ; TODO: {:?}\n", other));
            }
        }
    }

    for line in code {
        output.push_str(&line);
    }

    // Epilogue
    output.push_str("        mov     sp, fp\n");
    output.push_str("        pop     fp\n");
    output.push_str("        halt\n\n");

    Ok(output)
}
